version: 2

models:
  - name: dm_commodities
    description: "Datamart para dados de commodities integrados com movimentações"
    columns:
      - name: data
        description: "Data da observação"
      - name: ticker
        description: "Símbolo da commodity"
      - name: closing_value
        description: "Preço de fechamento da commodity"
      - name: action
        description: "Tipo de transação (buy/sell)"
      - name: quantity
        description: "Quantidade transacionada"
      - name: value
        description: "Valor da transação"
      - name: profit
        description: "Ganho ou perda da transação"