dw_commodities:
  outputs:
    dev:
      dbname: dw_commodities
      host: localhost
      pass: postgres
      port: 5432
      schema: dw_comm
      threads: 1
      type: postgres
      user: postgres
  target: dev
